spring.application.name=demo
spring.config.import=configserver:http://localhost:8888
#spring.datasource.platform=mysql
#spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
#spring.datasource.username=postgres
#spring.datasource.password=12345
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.admin.properties.auto.create.topics.enable=true
